### PR TITLE
fixed refresh repositories button icon

### LINKED ISSUE #726: Change the refresh graphic to a background definition
Currently we're using a the graphic parameter to set the refresh icon in the "Settings" tab when the "Refresh Repositories" button has been pressed to indicate that the repositories/scripts are currently refreshing. 
This approach has the disadvantage that the icon can't be resized, therefore we need to replace the graphic/`-fx-graphics` solution with a `-fx-background-image` one, which can be better adjusted.

The wanted design is that the refresh icon is shown in the left side of the button while next to it, in the right side, the "Refresh Repositories" text is shown.

```
-------------------------------
| Icon   Refresh Repositories |
-------------------------------
```

### PR DESCRIPTION
**Pull request by plata**
fixes #726

### CODE REVIEW

File: phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/settings/RepositoriesPanel.java [hunk 1]
```diff
@@ -169,6 +169,7 @@ private void populateRepositoryRefresh() {
         this.refreshRepositoriesLabel.setWrapText(true);
 
         this.refreshRepositoriesButton = new Button("Refresh Repositories");
+        refreshRepositoriesButton.getStyleClass().add("buttonWithIcon");
```
Comment (madoar) [inline phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/settings/RepositoriesPanel.java]: I would prefer, if this line starts with a `this.` because the other lines are written like this.

In addition I think we should define when we want to use the keyword `this` and when not, to do this uniformly.

**Comment by madoar** [comment]
Can you please provide a screenshot?
In addition it seems like Jenkins is currently on strike (maybe we should pay it better?^^)

File: phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/settings/RepositoriesPanel.java (hunk 1 above)
Comment (plata) [inline phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/settings/RepositoriesPanel.java]: Agree that we need a rule.

**Comment by plata** [comment]
refresh icon

I think @qparis is the only one who has the rights to fix Jenkins.

**Comment by qparis** [comment]
I don't understand, it seems that Jenkins works well isn't it?

**Comment by plata** [comment]
@qparis it did not run the after my push yesterday.

**Comment by madoar** [comment]
@plata it seems like a conflict occurred for this branch.

**Comment by madoar** [comment]
As far as I'm concerned we can merge this, what do you think @qparis?
